#pragma once

using namespace ATL;

template <class T>
class CProxy_IPerfRecorderEvents : public IConnectionPointImpl<T, &__uuidof( _IPerfRecorderEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
