#pragma once

using namespace ATL;

template <class T>
class CProxy_IPerfRecoderEvents : public IConnectionPointImpl<T, &__uuidof( _IPerfRecoderEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
